// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG1mlTuhWHfpyNu3Qu1rjjNh_cGsFDSmI',
    appId: '1:844651312647:web:63ed5e506be3ea83379ca2',
    messagingSenderId: '844651312647',
    projectId: 'yugtalk-7db69',
    authDomain: 'yugtalk-7db69.firebaseapp.com',
    storageBucket: 'yugtalk-7db69.appspot.com',
    measurementId: 'G-ZXH7P4FDM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HpI-UdFoE7fdm5FMqhGSyiw6zG9Ucdo',
    appId: '1:844651312647:android:711cee38d4137456379ca2',
    messagingSenderId: '844651312647',
    projectId: 'yugtalk-7db69',
    storageBucket: 'yugtalk-7db69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDUEkKoQh6m2FphuWQzua68AdNke3CxE',
    appId: '1:844651312647:ios:1f369e75512a91d7379ca2',
    messagingSenderId: '844651312647',
    projectId: 'yugtalk-7db69',
    storageBucket: 'yugtalk-7db69.appspot.com',
    iosBundleId: 'yugtalk.com.yugtalkTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwDUEkKoQh6m2FphuWQzua68AdNke3CxE',
    appId: '1:844651312647:ios:1f369e75512a91d7379ca2',
    messagingSenderId: '844651312647',
    projectId: 'yugtalk-7db69',
    storageBucket: 'yugtalk-7db69.appspot.com',
    iosBundleId: 'yugtalk.com.yugtalkTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG1mlTuhWHfpyNu3Qu1rjjNh_cGsFDSmI',
    appId: '1:844651312647:web:bb89a9a41c21a31f379ca2',
    messagingSenderId: '844651312647',
    projectId: 'yugtalk-7db69',
    authDomain: 'yugtalk-7db69.firebaseapp.com',
    storageBucket: 'yugtalk-7db69.appspot.com',
    measurementId: 'G-4TG8CD696S',
  );
}
